# Automatically generated by configure - do not modify
TARGET_AARCH64=y
TARGET_NAME=aarch64
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=aarch64
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/aarch64-core.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/aarch64-fpu.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/arm-core.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/arm-vfp.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/arm-vfp3.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/arm-neon.xml
CONFIG_I386_DIS=y
CONFIG_ARM_DIS=y
CONFIG_ARM_A64_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
