# Automatically generated by configure - do not modify
TARGET_PPC64=y
TARGET_NAME=ppc64
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/power64-core.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/power-fpu.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/power-altivec.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/power-spe.xml /home/ubuntu/go/src/github.com/hyperhq/qemu/gdb-xml/power-vsx.xml
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
